name: Publicar playlist

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos do repositório
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Descompactar playlist
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          mkdir -p public
          unzip -o tv_channels_806043140_plus.zip -d public

      - name: Preparar arquivos para publicação
        uses: actions/upload-pages-artifact@v4
        with:
          path: public

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
